# Created by newuser for 5.9

# https://thevaluable.dev/zsh-completion-guide-examples/
autoload -U compinit; compinit

source ~/.zsh_aliases

# https://starship.rs/guide/
eval "$(starship init zsh)"

echo ; neofetch
